### ISSUE TITLE
Config Option to "Hide" Vanilla Recipe Book doesn't work

### ISSUE THREAD

**Issue by SAFCxHarter** [blay09/CraftingTweaks#116] opened 2018-04-20 14:27 UTC
I have tired setting the option both in-game and in the config file. I have reset the game multiple times and it isn't working still, despite the fact the changelog for the latest version says it is fixed.

Forge Version: Forge-14.23.3.2669
Crafting Tweaks Version: Crafting Tweaks_1.12.2-8.1.8

Screenshots below!

Ingame Config Option
![ingame config options](https://user-images.githubusercontent.com/4738934/39056419-87a923c4-44ae-11e8-8300-a6c7d5421b9f.png)

Vanilla Crafting Table
![crafting table](https://user-images.githubusercontent.com/4738934/39056420-87c254de-44ae-11e8-8a2d-58b9a6f0a97a.png)

Config File
![config_optioncraftingtweaks](https://user-images.githubusercontent.com/4738934/39056461-a13694fc-44ae-11e8-82fd-ed555040bc08.png)

Tinkers Crafting Table
![craftinggridtinkers](https://user-images.githubusercontent.com/4738934/39057033-2ec62b74-44b0-11e8-9cc6-e7efcbd60d66.png)

**Comment by BlayTheNinth** [comment] 2018-04-24 09:03
Do you have a mod installed that replaces the Vanilla crafting tables or does anything else special to them? It seems to be working fine with just Forge and Crafting Tweaks, so a mod list would be good.

**Comment by jflewis23** [comment] 2018-04-25 14:42
With the following:
```
Minecraft 1.12.2
Forge 14.23.3.2655
Crafting Tweaks (1.12.2-8.1.8)
EnderIO (1.12.2-5.0.22)
```
I can confirm that Crafting Tweaks overlaps the vanilla recipe book and settings to disable it are essentially ignored. However, disabling EnderIO allows for the correct positioning of the book and the settings for hiding it are respected.

Please note:
I have not tested any other versions of Forge, Crafting Tweaks or EnderIO, nor have I made any changes to the configurations outside what is stated. Information is provided as-is.

**Comment by jflewis23** [comment] 2018-04-25 16:50
With:
```
Minecraft 1.12.2
Forge 14.23.3.2655
Crafting Tweaks 8.1.8
```
and
```
Just Enough Items (4.8.5.147)
EnderIO (5.0.22)
```
(and a few other mods)

I have found that the book is overlapped by the Crafting Tweaks buttons on the UI for vanilla crafting table, and the settings are not respected when hiding the book.

However, if running either EnderIO or JEI independently causes no issue. In this case, the settings for hiding the book are respected and the vanilla book appears in the top-right corner of the crafting menu UI for the vanilla crafting table (as opposed to the left, where Crafting Tweaks buttons overlap it).

Please note:
I cannot comment on whether there are any settings from either of the aforementioned mods that can mitigate this or whether there are any additional factors, but perhaps this can give some pointers to the problem and whether it may be an issue that needs to be resolved in another mod. Furthermore, I have not tried any other versions of the above mods.

**Comment by BlayTheNinth** [comment] 2018-04-25 17:28
Thanks, I've reported the issue to Ender IO. For the time being, the Ender IO config has options to disable their recipe button tweaks.

**Comment by jflewis23** [comment] 2018-04-25 18:17
For clarity, it seems that would be a change in line 731 of enderio/EnderIO.cfg, setting the following option to from `true` to `false`:
`B:recipeButtonReplaceWithJei=false`
The comment above (on line 730) says:
> Should the annoying recipe button be replaced with a JEI recipe button if JEI is installed?

Anyway, with this change the Crafting Tweaks buttons no longer overlap the button (as the guide book will appear in the top-right of the crafting window for the vanilla crafting table) and it will respect the settings set in Crafting Tweaks for whether the book is hidden.

I cannot comment on whether it is something to do with EnderIO or an underlying issue with JEI since I haven't extensively looked into those two mods. But this is a good mitigation in the meantime.

**Comment by BlayTheNinth** [comment] 2018-05-15 15:11
Released a workaround for this so my mod stops looking like it's completely broken.

**Closed as completed by BlayTheNinth** 2018-05-15 15:11 UTC
Labels: Bug, Caused by Another Mod
