### ISSUE TITLE
[1.19.2] Weird duplication bug

### ISSUE THREAD

**Issue by vizthex123** [blay09/CraftingTweaks#212] opened 2024-04-12 01:09 UTC
### Minecraft Version

Other (specify below)

### Mod Loader

Forge

### Mod Loader Version

Fabric 0.15.9

### Mod Version

15.1.9

### Balm Version

4.6.0

### Describe the Issue

Every so often when I craft an item, I'll get the result without the game consuming the input - leading to said item(s) being duplicated.

The game doesn't delete the duplicates (nor does it seem to even recognize the bug, as the game doesn't crash or anything), so I'm not sure what's going on.

### Logs

https://gist.github.com/vizthex123/46cab1aa3c528e50e420968e9461cf8e

### Do you use any performance-enhancing mods (e.g. OptiFine) or custom server distributions (e.g. SpongeForge)?

FastLoad, FerriteCore, ModernFix, Sodium, and Starlight

**Comment by BlayTheNinth** [comment] 2024-06-02 06:59
Closing since 1.19.2 is no longer supported. If this happens in later versions, more information on how to reproduce the issue is needed.

**Closed as not planned by BlayTheNinth** 2024-06-02 06:59 UTC
Labels: Bug, Needs Repro, EOL
