### ISSUE TITLE
Crash when entering world in dev env

### ISSUE THREAD

**Issue by Luligabi1** [blay09/CraftingTweaks#193] opened 2023-05-02 19:35 UTC
### Minecraft Version

1.19.4

### Mod Loader

Fabric

### Mod Loader Version

Loader 0.14.19, API 0.78.0+1.19.4

### Mod Version

17.0.2

### Balm Version

6.0.2

### Describe the Issue

The game crashes as soon as a world is loaded.

1. Open the game (at this point there's already some mixin-related issues spewed on the console);
2. Open a world;
3. Crash

### Logs

https://pastebin.com/dyLuj7k9

### Do you use any performance-enhancing mods (e.g. OptiFine) or custom server distributions (e.g. SpongeForge)?

No

**Comment by Luligabi1** [comment] 2023-05-02 19:36
I forgot to mention on the description, but this happened on development environment; not sure if it happens outside it.

**Comment by Luligabi1** [comment] 2023-06-18 04:35
~~Could reproduce on CT `1.20-18.0.1` and Balm `1.20-7.0.3` too.~~

Could reproduce on CT `1.20-18.0.2` and Balm `1.20-7.0.4`

**Comment by BlayTheNinth** [comment] 2023-07-10 09:05
Unfortunately, I've never been able to track down why this is happening to some dev environments. I've never had an issue on my environments and others have reported that the issue magically went away for them, while others never ran into it in the first place.

Perhaps someone more knowledgeable about Loom / Mixin will be able to to locate the problem.

**Comment by unilock** [comment] 2023-08-08 13:11
It seems the issue is fixed by removing [ModelLayersAccessor](https://github.com/TwelveIterationMods/Balm/blob/1.20.x/shared/src/main/java/net/blay09/mods/balm/mixin/ModelLayersAccessor.java). (https://github.com/Luligabi1/EnhancedWorkbenches/pull/3#issuecomment-1665742600)

What's that mixin for, anyway? It doesn't appear to be used anywhere.

**Closed as completed** 2023-09-14 10:33 UTC
Labels: Bug, Crash
