### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by MechanicalOrder** [blay09/CraftingTweaks#131] opened 2019-10-16 20:19 UTC
CraftingTweaks: 1.12.2-8.1.9
Forge: 14.23.5.2847
Java: 1.8.0_221
Description: Got this crash while testing my mods on creative, i was in the inventory.

Crash log: https://pastebin.com/zwn7y2hW

**Comment by BlayTheNinth** [comment] 2020-01-18 15:13
Closing since it seems to be an isolated issue and I can't reproduce it.

**Closed as completed by BlayTheNinth** 2020-01-18 15:13 UTC
Labels: Bug, Crash
