### ISSUE TITLE
Ae2 Crafting terminal

### ISSUE THREAD

**Issue by unknownSold** [blay09/CraftingTweaks#125] opened 2019-08-28 14:25 UTC
Please add support for Ae2 in 1.12.2

**Comment by Skydragonsz** [comment] 2019-08-28 14:29
From https://blay09.gitlab.io/mod-docs/#/faq

> Can I connect an Applied Energistics/Refined Storage network to my kitchen?
> * No, and it is very unlikely to ever happen.

**Comment by BlayTheNinth** [comment] 2019-08-28 15:51
Duplicate of #98

**Closed as completed by BlayTheNinth** 2019-08-28 15:51 UTC
Labels: Feature, Duplicate
