### ISSUE TITLE
Crash when both CraftingTweaks and InventoryEssentials are both installed

### ISSUE THREAD

**Issue by magcicada** [blay09/CraftingTweaks#233] opened 2024-12-13 12:33 UTC
### Minecraft Version

1.20.1 (LTS)

### Mod Loader

NeoForge

### Mod Version

18.2.5

### Describe the Issue

The game will crash when CraftingTweaks and InventoryEssentials are both installed. It works fine if either one is installed separately.

### Logs

https://mclo.gs/0oeVDQL

**Comment by 0xRowie** [comment] 2024-12-13 13:17
I'm having the exact same issue on Forge.

Minecraft Version : 1.20.1
Mod Loader: Forge (47.3.0)

CraftingTweaks: 18.2.5
InventoryEssentials: 8.2.6
Balm 7.3.9

EDIT: 
I've tested a modpack that contains the same exact versions as written above and the crash does not appear to be happening at all. Created a duplicate of said modpack (manually creating new modpack in curseforge and manually adding the same mods and versions) and the crash appears again however not on every startup. 

Attempted to start the game 10 times, 3 times it loaded in correctly without crashes the other 7 times the crash either occurs at craftingtweaks or inventoryessentials.

**Comment by BlayTheNinth** [comment] 2024-12-17 19:54
Fixed in Balm 7.3.10

**Closed as completed by BlayTheNinth** 2024-12-17 19:54 UTC
Labels: Bug, Crash, NeoForge, Forge
