### ISSUE TITLE
[craftingtweaks:network] rejected their server side version number during listping

### ISSUE THREAD

**Issue by frakier** [blay09/CraftingTweaks#178] opened 2022-10-05 20:46 UTC
### Minecraft Version

1.18.x

### Mod Loader

Forge

### Mod Loader Version

40.1.0

### Mod Version

tired both craftingtweaks-forge-1.18.1-14.0.2 and craftingtweaks-forge-1.18.2-14.0.3

### Describe the Issue

MC 1.18.2
Forge 40.1.0
Java 17.0.1

[craftingtweaks:network] rejected their server side version number

Updated Balm from balm-3.1.0+0 to balm-3.2.0+0 to see if that helped but no luck.

If it helps this it the Create Flavor 4.1... and I added the CraftingTweaks mod on the client because for me it is like the old American Express commercial "Don't Leave Home Without It". Figured since CraftingTweaks  works regardless it would not hurt anything.
I know the server zip does not have CraftingTweaks in the mods folder... will ask the owner if they have put one in themselves to be sure.

### Do you use any performance-enhancing mods (e.g. OptiFine)?

No OptFine but nowadays who knows... I used rubidium though

**Comment by wchristian** [comment] 2022-12-12 11:33
duplicate of #176

**Comment by BlayTheNinth** [comment] 2023-01-23 17:10
Duplicate of #176

**Closed as not planned by BlayTheNinth** 2023-01-23 17:10 UTC
Labels: Bug, Duplicate
